import { StyleSheet } from '@react-pdf/renderer'

export const ticketPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingHorizontal: 28,
    paddingBottom: 24,
    fontFamily: 'Helvetica',
    fontSize: 10,
    color: '#111827',
    backgroundColor: '#ffffff',
  },
  pageShell: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 12,
    overflow: 'hidden',
  },
  accentBar: {
    height: 6,
    backgroundColor: '#0f7bff',
  },
  section: {
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  sectionBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  title: {
    fontSize: 20,
    fontWeight: 700,
    color: '#0f172a',
  },
  subtitle: {
    marginTop: 4,
    fontSize: 9,
    color: '#6b7280',
  },
  banner: {
    backgroundColor: '#ecfdf5',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
  },
  bannerLabel: {
    fontSize: 10,
    fontWeight: 700,
    color: '#166534',
  },
  bannerText: {
    marginTop: 3,
    fontSize: 9,
    color: '#15803d',
  },
  metaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  metaCard: {
    minWidth: '31%',
    flexGrow: 1,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  metaLabel: {
    fontSize: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#6b7280',
    marginBottom: 3,
  },
  metaValue: {
    fontSize: 10,
    fontWeight: 700,
    color: '#111827',
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8fafc',
    borderBottomWidth: 1,
    borderBottomColor: '#dbe2ea',
  },
  tableHeaderCell: {
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRightWidth: 1,
    borderRightColor: '#dbe2ea',
    fontSize: 8,
    fontWeight: 700,
    color: '#475569',
  },
  tableCell: {
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRightWidth: 1,
    borderRightColor: '#e5e7eb',
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  rowAlt: {
    backgroundColor: '#ffffff',
  },
  rowMuted: {
    backgroundColor: '#f8fafc',
  },
  flightAirline: {
    fontSize: 10,
    fontWeight: 700,
    color: '#111827',
  },
  flightNumber: {
    marginTop: 2,
    fontSize: 8,
    color: '#475569',
  },
  cabin: {
    marginTop: 2,
    fontSize: 8,
    color: '#0f7bff',
  },
  city: {
    fontSize: 10,
    fontWeight: 700,
    color: '#111827',
  },
  airport: {
    marginTop: 2,
    fontSize: 8,
    color: '#6b7280',
  },
  time: {
    fontSize: 10,
    fontWeight: 700,
    color: '#0f7bff',
  },
  date: {
    marginTop: 2,
    fontSize: 7.5,
    color: '#0f7bff',
  },
  stopBadge: {
    minWidth: 66,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    textAlign: 'center',
    fontSize: 8,
    fontWeight: 700,
    color: '#475569',
  },
  stopTitle: {
    fontSize: 9,
    fontWeight: 700,
    color: '#0f7bff',
    marginBottom: 3,
  },
  stopText: {
    fontSize: 8,
    color: '#6b7280',
  },
  termsTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: '#111827',
    marginBottom: 8,
  },
  termsSectionTitle: {
    fontSize: 9,
    fontWeight: 700,
    color: '#111827',
    marginBottom: 6,
  },
  bulletRow: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  bullet: {
    width: 10,
    color: '#0f7bff',
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1.4,
  },
  bulletText: {
    flex: 1,
    fontSize: 8.5,
    color: '#475569',
    lineHeight: 1.45,
  },
  footer: {
    marginTop: 12,
    paddingHorizontal: 18,
    paddingBottom: 16,
    fontSize: 8,
    color: '#6b7280',
    textAlign: 'center',
  },
})
